export const dummyData = [
    {
        trackId: 2106100058,
        title: "Tears of the Fallen Angel",
        version: "",
        artist: "Marc Brauner",
        label: "Shall Not Fade",
        image: "http://i3.ytimg.com/vi/mVX7YsaF_9o/maxresdefault.jpg",
        filename: "Marc-Brauner-Tears-Of-The-Fallen-Angel.mp3",
        buyUrl: "https://www.beatport.com/track/tears-of-the-fallen-angel/14827129",
    },
    {
        title: "Sylvestre Alone",
        version: "",
        artist: "DJOKO",
        label: "Shall Not Fade",
        image: "http://i3.ytimg.com/vi/9jEvskW-PA0/maxresdefault.jpg",
        filename: "DJOKO-Sylvestre-Alone.mp3",
        buyUrl: "https://djoko.bandcamp.com/track/sylvestre-alone",
    },
    {
        title: "Let’s Try",
        version: "",
        artist: "Dario D'Attis, Markus Homm",
        label: "Saved",
        image: "https://i3.ytimg.com/vi/Cw-uMfFGWL8/maxresdefault.jpg",
        filename: "Dario-DAttis-Markus-Homm-Lets-Try.mp3",
        buyUrl: "https://www.traxsource.com/track/8546951/lets-try-extended-mix",
    },
    {
        title: "Break For Lovers",
        version: "Elinov Edit",
        artist: "Men I Trust",
        label: "White Label",
        image: "http://i3.ytimg.com/vi/2JCGnqOBpJE/maxresdefault.jpg",
        filename: "Men-I-Trust-Break-For-Lovers-Elinov-Edit.mp3",
        buyUrl: "https://hypeddit.com/track/ksgko5",
    },
    {
        title: "Sense Of Closure",
        version: "",
        artist: "3 S",
        label: "White Label",
        image: "http://i3.ytimg.com/vi/N7iiWBRJHyw/maxresdefault.jpg",
        filename: "3-S-Sense-Of-Closure.mp3",
        buyUrl: "https://3smusique.bandcamp.com/track/sense-of-closure",
    },
    {
        title: "Italia Chic",
        version: "",
        artist: "KOKO",
        label: "White Label",
        image: "http://i3.ytimg.com/vi/klxNS-RKxe0/maxresdefault.jpg",
        filename: "KOKO Italia-Chic.mp3",
        buyUrl: "https://koko18.bandcamp.com/track/koko-italia-chic",
    },
];
